### ISSUE TITLE
为什么下载后，文件打不开

### ISSUE THREAD

**Issue by louisZL** [gopherchina/conference#1]
下载后，文件打开时提示文件格式错误

**Comment by astaxie** [comment]
你是用什么工具打开你本地的pdf文件的？

**Comment by ghost** [comment]
@astaxie 使用mac自带的pdf软件打不开。

**Comment by kkdai** [comment]
Works well on my computer  - OSX 10.11.4
@zwb-ict  @louisZL  you might need to specific your problem file name and link

**Comment by ghost** [comment]
@kkdai @astaxie Sorry, through click download zip. It's OK. Last time, I download one file with chrome right button, which made file cann't be open.
