### ISSUE TITLE
请问有本次大会的视频录像么

### ISSUE THREAD

**Issue by QuantumGhost** [gopherchina/conference#2]
如题，希望能够回顾一下错过的演讲

**Comment by ipfans** [comment]
大概没有，StuQ有直播，不知道有没有人录

**Comment by liuhui244671426** [comment]
有视频资料么?

**Comment by jatsmulator** [comment]
没去参加, 怎么领T恤?

2017-04-17 18:51 GMT+08:00 liuhui244671426 <notifications@github.com>:

**Comment by KISSMonX** [comment]
想要 技术 party 之夜的视频录像. 哈哈哈

**Comment by ddatsh** [comment]
youtube 上有2017视频的

**Comment by langgo** [comment]
https://www.youtube.com/playlist?list=PLx_Mc4dJcQbl4qPWbVu86u6owZeiwsErR

**Comment by TUTUBIG** [comment]
不是说会对参会人员免费的么

**Comment by ipfans** [comment]
注意时间是一年以前啊…

**Comment by gqdw** [comment]
求视频

**Comment by jaylu163** [comment]
求视频
